name: saveit
description: "SaveIt App"

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

#------------------ PACKAGES ------------------#
dependencies:
  flutter:
    sdk: flutter

  # icons
  
  cupertino_icons: ^1.0.6
  iconsax: ^0.0.8

  # utility packages

  http: ^1.2.1
  intl: ^0.19.0
  logger: ^2.2.0
  url_launcher: ^6.2.6
  flutter_native_splash: ^2.4.0
  smooth_page_indicator: ^1.1.0
  intl_phone_field: ^3.2.0
  curved_navigation_bar: ^1.0.3
  flutter_slidable: ^3.1.0

  # state managment

  get: ^4.6.6
  get_storage: ^2.1.1
  firebase_core: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  carousel_slider: ^4.2.1

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  #------------------ LOCAL ASSETS ------------------#
  assets:
    - assets/images/on_board_images/
    - assets/images/welcome_images/
    - assets/logos/
    - assets/images/login_image/
    - assets/images/home/
    - assets/icons/
    - assets/images/recomanded/
    - assets/images/recomanded/header/
    - assets/images/vigitabs/
    - assets/images/storecloths/
    - assets/images/recomanded/recomnd/
    
    
    
    
    

  #------------------ LOCAL FONTS ------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
