// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATL9PNdi20Gr-HJpWxavmG2Ta9tY35xDk',
    appId: '1:784458115422:web:265d94730da2ec7a0847cf',
    messagingSenderId: '784458115422',
    projectId: 'saveit-ef6ec',
    authDomain: 'saveit-ef6ec.firebaseapp.com',
    storageBucket: 'saveit-ef6ec.appspot.com',
    measurementId: 'G-KR8B3V17HR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUzScQ08XBHRU_-Auaj_2KxgvmdTZ1anw',
    appId: '1:784458115422:android:946cb079d21fcfbc0847cf',
    messagingSenderId: '784458115422',
    projectId: 'saveit-ef6ec',
    storageBucket: 'saveit-ef6ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCLq0DuWYRsiPsJrzF3ohqn46I0XBj-E0',
    appId: '1:784458115422:ios:7693b4c38db5d3920847cf',
    messagingSenderId: '784458115422',
    projectId: 'saveit-ef6ec',
    storageBucket: 'saveit-ef6ec.appspot.com',
    iosBundleId: 'com.example.saveit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCLq0DuWYRsiPsJrzF3ohqn46I0XBj-E0',
    appId: '1:784458115422:ios:7693b4c38db5d3920847cf',
    messagingSenderId: '784458115422',
    projectId: 'saveit-ef6ec',
    storageBucket: 'saveit-ef6ec.appspot.com',
    iosBundleId: 'com.example.saveit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATL9PNdi20Gr-HJpWxavmG2Ta9tY35xDk',
    appId: '1:784458115422:web:1c9d0a65252b8dcc0847cf',
    messagingSenderId: '784458115422',
    projectId: 'saveit-ef6ec',
    authDomain: 'saveit-ef6ec.firebaseapp.com',
    storageBucket: 'saveit-ef6ec.appspot.com',
    measurementId: 'G-581H4KTH1Y',
  );

}